version: "3"
services:
  grafana:
    image: grafana/grafana:8.2.2
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 1
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: marcusolsson-static-datasource
    volumes:
      - ./provisioning:/etc/grafana/provisioning
